## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [4]:
from sklearn.model_selection import train_test_split, KFold
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
X_train

array([[210, 211, 212, 213, 214],
       [945, 946, 947, 948, 949],
       [450, 451, 452, 453, 454],
       [680, 681, 682, 683, 684],
       [255, 256, 257, 258, 259],
       [635, 636, 637, 638, 639],
       [810, 811, 812, 813, 814],
       [205, 206, 207, 208, 209],
       [590, 591, 592, 593, 594],
       [565, 566, 567, 568, 569],
       [130, 131, 132, 133, 134],
       [695, 696, 697, 698, 699],
       [500, 501, 502, 503, 504],
       [555, 556, 557, 558, 559],
       [ 10,  11,  12,  13,  14],
       [385, 386, 387, 388, 389],
       [230, 231, 232, 233, 234],
       [935, 936, 937, 938, 939],
       [955, 956, 957, 958, 959],
       [425, 426, 427, 428, 429],
       [805, 806, 807, 808, 809],
       [180, 181, 182, 183, 184],
       [950, 951, 952, 953, 954],
       [305, 306, 307, 308, 309],
       [110, 111, 112, 113, 114],
       [705, 706, 707, 708, 709],
       [505, 506, 507, 508, 509],
       [165, 166, 167, 168, 169],
       [ 55,  56,  57,  58,  59],
       [970, 971, 972, 973, 974],
       [795, 796, 797, 798, 799],
       [ 30,  31,  32,  33,  34],
       [135, 136, 137, 138, 139],
       [600, 601, 602, 603, 604],
       [ 20,  21,  22,  23,  24],
       [160, 161, 162, 163, 164],
       [710, 711, 712, 713, 714],
       [725, 726, 727, 728, 729],
       [545, 546, 547, 548, 549],
       [720, 721, 722, 723, 724],
       [ 50,  51,  52,  53,  54],
       [310, 311, 312, 313, 314],
       [560, 561, 562, 563, 564],
       [730, 731, 732, 733, 734],
       [830, 831, 832, 833, 834],
       [  0,   1,   2,   3,   4],
       [990, 991, 992, 993, 994],
       [765, 766, 767, 768, 769],
       [350, 351, 352, 353, 354],
       [615, 616, 617, 618, 619],
       [320, 321, 322, 323, 324],
       [220, 221, 222, 223, 224],
       [815, 816, 817, 818, 819],
       [140, 141, 142, 143, 144],
       [200, 201, 202, 203, 204],
       [540, 541, 542, 543, 544],
       [775, 776, 777, 778, 779],
       [780, 781, 782, 783, 784],
       [125, 126, 127, 128, 129],
       [115, 116, 117, 118, 119],
       [920, 921, 922, 923, 924],
       [735, 736, 737, 738, 739],
       [405, 406, 407, 408, 409],
       [195, 196, 197, 198, 199],
       [840, 841, 842, 843, 844],
       [235, 236, 237, 238, 239],
       [470, 471, 472, 473, 474],
       [770, 771, 772, 773, 774],
       [215, 216, 217, 218, 219],
       [690, 691, 692, 693, 694],
       [ 15,  16,  17,  18,  19],
       [525, 526, 527, 528, 529],
       [265, 266, 267, 268, 269],
       [665, 666, 667, 668, 669],
       [900, 901, 902, 903, 904],
       [890, 891, 892, 893, 894],
       [925, 926, 927, 928, 929],
       [245, 246, 247, 248, 249],
       [400, 401, 402, 403, 404],
       [170, 171, 172, 173, 174],
       [ 35,  36,  37,  38,  39],
       [550, 551, 552, 553, 554],
       [455, 456, 457, 458, 459],
       [415, 416, 417, 418, 419],
       [880, 881, 882, 883, 884],
       [905, 906, 907, 908, 909],
       [445, 446, 447, 448, 449],
       [ 40,  41,  42,  43,  44],
       [ 65,  66,  67,  68,  69],
       [295, 296, 297, 298, 299],
       [855, 856, 857, 858, 859],
       [655, 656, 657, 658, 659],
       [ 85,  86,  87,  88,  89],
       [360, 361, 362, 363, 364],
       [875, 876, 877, 878, 879],
       [670, 671, 672, 673, 674],
       [835, 836, 837, 838, 839],
       [915, 916, 917, 918, 919],
       [315, 316, 317, 318, 319],
       [270, 271, 272, 273, 274],
       [535, 536, 537, 538, 539],
       [250, 251, 252, 253, 254],
       [980, 981, 982, 983, 984],
       [290, 291, 292, 293, 294],
       [240, 241, 242, 243, 244],
       [440, 441, 442, 443, 444],
       [105, 106, 107, 108, 109],
       [285, 286, 287, 288, 289],
       [800, 801, 802, 803, 804],
       [960, 961, 962, 963, 964],
       [645, 646, 647, 648, 649],
       [185, 186, 187, 188, 189],
       [785, 786, 787, 788, 789],
       [965, 966, 967, 968, 969],
       [  5,   6,   7,   8,   9],
       [260, 261, 262, 263, 264],
       [745, 746, 747, 748, 749],
       [650, 651, 652, 653, 654],
       [755, 756, 757, 758, 759],
       [515, 516, 517, 518, 519],
       [495, 496, 497, 498, 499],
       [580, 581, 582, 583, 584],
       [435, 436, 437, 438, 439],
       [370, 371, 372, 373, 374],
       [605, 606, 607, 608, 609],
       [995, 996, 997, 998, 999],
       [100, 101, 102, 103, 104],
       [940, 941, 942, 943, 944],
       [355, 356, 357, 358, 359],
       [530, 531, 532, 533, 534],
       [ 70,  71,  72,  73,  74],
       [460, 461, 462, 463, 464],
       [895, 896, 897, 898, 899],
       [510, 511, 512, 513, 514]])

In [6]:
X_test

array([[475, 476, 477, 478, 479],
       [ 75,  76,  77,  78,  79],
       [150, 151, 152, 153, 154],
       [790, 791, 792, 793, 794],
       [640, 641, 642, 643, 644],
       [575, 576, 577, 578, 579],
       [345, 346, 347, 348, 349],
       [850, 851, 852, 853, 854],
       [870, 871, 872, 873, 874],
       [225, 226, 227, 228, 229],
       [330, 331, 332, 333, 334],
       [910, 911, 912, 913, 914],
       [825, 826, 827, 828, 829],
       [390, 391, 392, 393, 394],
       [930, 931, 932, 933, 934],
       [885, 886, 887, 888, 889],
       [280, 281, 282, 283, 284],
       [760, 761, 762, 763, 764],
       [410, 411, 412, 413, 414],
       [340, 341, 342, 343, 344],
       [620, 621, 622, 623, 624],
       [ 80,  81,  82,  83,  84],
       [740, 741, 742, 743, 744],
       [465, 466, 467, 468, 469],
       [325, 326, 327, 328, 329],
       [300, 301, 302, 303, 304],
       [420, 421, 422, 423, 424],
       [335, 336, 337, 338, 339],
       [625, 626, 627, 628, 629],
       [660, 661, 662, 663, 664],
       [ 45,  46,  47,  48,  49],
       [ 90,  91,  92,  93,  94],
       [275, 276, 277, 278, 279],
       [375, 376, 377, 378, 379],
       [750, 751, 752, 753, 754],
       [520, 521, 522, 523, 524],
       [675, 676, 677, 678, 679],
       [685, 686, 687, 688, 689],
       [820, 821, 822, 823, 824],
       [380, 381, 382, 383, 384],
       [395, 396, 397, 398, 399],
       [985, 986, 987, 988, 989],
       [190, 191, 192, 193, 194],
       [120, 121, 122, 123, 124],
       [610, 611, 612, 613, 614],
       [975, 976, 977, 978, 979],
       [145, 146, 147, 148, 149],
       [ 95,  96,  97,  98,  99],
       [715, 716, 717, 718, 719],
       [430, 431, 432, 433, 434],
       [570, 571, 572, 573, 574],
       [865, 866, 867, 868, 869],
       [ 25,  26,  27,  28,  29],
       [630, 631, 632, 633, 634],
       [585, 586, 587, 588, 589],
       [365, 366, 367, 368, 369],
       [700, 701, 702, 703, 704],
       [490, 491, 492, 493, 494],
       [860, 861, 862, 863, 864],
       [480, 481, 482, 483, 484],
       [845, 846, 847, 848, 849],
       [485, 486, 487, 488, 489],
       [155, 156, 157, 158, 159],
       [ 60,  61,  62,  63,  64],
       [175, 176, 177, 178, 179],
       [595, 596, 597, 598, 599]])

In [7]:
y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

In [8]:
y_test

array([0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.])

In [9]:
#可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)
y_1_index, y_0_index = np.where(y==1)[0], np.where(y==0)[0] # 選出 y 等於 1 的 index 與 y 等於 0 的 index

In [10]:
y_1_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [11]:
train_data_y1, test_data_y1, train_label_y1, test_label_y1 = train_test_split(X[y_1_index], y[y_1_index], test_size=10)
train_data_y0, test_data_y0, train_label_y0, test_label_y0 = train_test_split(X[y_0_index], y[y_0_index], test_size=10)

In [12]:
# 將 (X, y) 中 y 等於 1 的部分取出作 train/test split，指定 test_size=10； y 等於 0 的部分也做一樣的操作
train_data_y1, test_data_y1, train_label_y1, test_label_y1 = train_test_split(X[y_1_index], y[y_1_index], test_size=10)
train_data_y0, test_data_y0, train_label_y0, test_label_y0 = train_test_split(X[y_0_index], y[y_0_index], test_size=10)

In [13]:
#再將分好的 data 與 label 合併起來，變回我們熟悉的 x_train, x_test, y_train, y_test
x_train, y_train = np.concatenate([train_data_y1, train_data_y0]), np.concatenate([train_label_y1, train_label_y0])
x_test, y_test = np.concatenate([test_data_y1, test_data_y0]), np.concatenate([test_label_y1, test_label_y0])

In [14]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])